epochs: 100
log_wandb: 1
model: "WSCNN"
visualize: 1
augment: 1
hidden_channels: 32
batch_size: 64
seed: 0
learning_rate: 0.01
learning_rate_reps: 0.01
norm_scaler: 0.1
entropy_scaler: 0.0
cuda: 1
group: "so(2)"
transform_labels: "all"
n_group: 4
n_iter: 20
init_mode: "rand"
num_layers: 4
kernel_size: 5
fix_identity: 1
dataset: "rotatedmnist"