batch_size: 128
epochs: 200
seed: 0
learning_rate: 1e-4
learning_rate_reps: 1e-2
norm_scaler: 0.1
entropy_scaler: 0.0
cuda: 1
log_wandb: 1
n_group: 4
n_iter: 20
hidden_channels: 32
model: "WSResNet"
init_mode: "rand"
visualize: 0
augment: 0
kernel_size: 7
fix_identity: 1
dataset: "cifar10"
